### PR TITLE
+ .gitignore

### PR DESCRIPTION
**Pull request by kissarat**

### CODE REVIEW

**Comment by kissarat** [comment]
I have got errors when running python3 -m unittest discover .
http://pastebin.com/LpdMAdmG

**Comment by xolox** [comment]
Hi Taras and thanks for the feedback. I assume your pull request and the later comment are unrelated to each other, so I will reply to each individually below.

### About the `.gitignore` additions

None of the patterns you've added to the `.gitignore` file are specific to the py2deb project, so I don't see the value of adding these to a project specific `.gitignore` file. Several points to note:

1. I've never used an [IDE](http://en.wikipedia.org/wiki/Integrated_development_environment) to work on Python projects (just Vim with plug-ins for me :-) so why would I exclude IDE specific directories in a project's `.gitignore` file? I similarly don't exclude [Vim swap files](http://vimdoc.sourceforge.net/htmldoc/recover.html#swap-file) in project specific `.gitignore` files (because it's not specific to the project).

2. If I start doing this now for IDEA I can proceed to do the same thing for every IDE in the world that can be used for Python development. That seems really strange to me and implies that there should be a better solution, which there is! (see the next point)

3. What I do instead for these kinds of things is to add the following to my `~/.gitconfig` file:

 ```dosini
[core]
  excludesfile = ~/.cvsignore
```

 My `~/.cvsignore` file looks like this:

 ```
*.egg
*.egg-info/
*.mo
*.patch
*.pyc
*~
.*.s??
.*.sw?
.coverage
.DS_Store
.hidden
.s??
.sw?
.tox
build/
dist/*.tar.gz
htmlcov
tags
```

 I suggest you use the same approach (with your own choice of patterns to ignore of course) so that you don't have to see things like the `.idea` directory in git's list of untracked files, but without having to bother every Python project you're working on about the fact that you use an IDE that creates hidden directories/files inside git checkouts.

### About the Python 3 test failures

**First a disclaimer / public service announcement:** The py2deb test suite has been running fine on my systems for months now (based on [Tox](http://codespeak.net/tox/) and the [deadsnakes PPA](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes)), but I've only just made the py2deb project public and the test suite isn't properly running on Travis CI yet due to their apparent use of custom compiled Pythons (I need to investigate this further in the coming days).

**Then about the specific error in the output you posted:** I assume you're referring to the following output:

```
Traceback (most recent call last):
  File "/home/taras/forks/py2deb/py2deb/cli.py", line 184, in main
    archives, relationships = converter.convert(arguments)
  File "/home/taras/forks/py2deb/py2deb/converter.py", line 371, in convert
    for package in self.get_source_distributions(pip_install_arguments, sources_directory):
  File "/home/taras/forks/py2deb/py2deb/converter.py", line 426, in get_source_distributions
    for requirement in self.pip_accel.get_requirements(arguments):
  File "/usr/local/lib/python3.4/dist-packages/pip_accel/__init__.py", line 197, in get_requirements
    return self.unpack_source_dists(arguments)
  File "/usr/local/lib/python3.4/dist-packages/pip_accel/__init__.py", line 244, in unpack_source_dists
    requirements = self.get_pip_requirement_set(arguments, use_remote_index=False)
  File "/usr/local/lib/python3.4/dist-packages/pip_accel/__init__.py", line 305, in get_pip_requirement_set
    cmd_name, options, args, parser = parseopts(command_line[1:])
ValueError: need more than 2 values to unpack
```

I think this is the issue reported in paylogic/pip-accel#23 (running against a version of pip that is too new) but the pip requirement of pip-accel was pinned to a "known working" version so you shouldn't be getting this error if you installed things properly.

If you create a clean Python 3.4 virtual environment and install py2deb and its dependencies there, do you still get the same error?

**Comment by kissarat** [comment]
I want to participate but your tests failed on my computer. So I just commit .gitignore .
I don't understand why you use improved editor instead of clever developer environment than show all your faults at once (at least)

**Comment by xolox** [comment]
> I want to participate but your tests failed on my computer. So I just commit .gitignore.

I appreciate that you want to participate, which is why I gave a detailed reply instead of just ignoring or closing the pull request. You didn't reply to my previous message where I tried to reason about the test failure. I can provide one more hint that might get us further:

I run the test suite on multiple Python versions using [Tox](http://codespeak.net/tox/) to guarantee a clean test environment for every run of the test suite. When you install Tox (`pip install tox`) and run it without any arguments it will run the test suite for all available environments, but you can also choose to run the test suite using Tox for specific environments. For example the following command runs the test suite specifically for Python 3.4:

    $ tox -e py34

The test suite takes a while but eventually this ends as follows for me:

```
py34: commands succeeded
congratulations :)
```

Can you reproduce the errors you showed previously when you run the test suite like this?

> I don't understand why you use improved editor instead of clever developer environment than shows (at least) all your faults at once

I honestly can't tell if your being serious or tongue in cheek here, so I will reply based on the first possibility:

I like that everyone gets to choose their own development environment with Python, there is no single right way to develop for Python. In my case I've been working in Vim for years and have become very proficient at it. I've even started learning to extend Vim with custom plug-ins [which I publish as open source for everyone to use freely](https://github.com/search?q=user%3Axolox+language%3Avim).

If you don't like Vim or prefer your own environment, that's great, good for you! But let's not get into an [editor war](http://en.wikipedia.org/wiki/Editor_war) here ;-).

**Comment by kissarat** [comment]
*.egg
*.egg-info/
*.mo
*.patch
*.pyc
.coverage
.DS_Store
.hidden
build/
dist/*.tar.gz
htmlcov
tags

is common so you must add it to .gitignore . You ought not create folders that may use popular IDE and nothing happen when you add .idea to ignore

**Comment by xolox** [comment]
Thanks for the pull request, I included the suggestions which make sense to the project.

**Pull request merged**
